/**
 * Device identity and registration types
 * @module device
 */

/**
 * Base64url encoded string type
 */
export type Base64Url = string;

/**
 * Device ID - SHA-256 hash of Ed25519 public key
 */
export type DeviceId = string;

/**
 * Worker-generated message ID
 */
export type MessageId = string;

/**
 * Timestamp in milliseconds
 */
export type TimestampMs = number;

/**
 * Device roles in the health relay system
 */
export type DeviceRole = "ios" | "gateway";

/**
 * Request to register a device with the relay
 */
export interface RegisterDeviceRequest {
  /** Device ID (SHA-256 of Ed25519 public key) */
  deviceId: DeviceId;
  /** Ed25519 public key (base64url, 32 bytes raw) */
  publicKey: Base64Url;
  /** Device role */
  role: DeviceRole;
  /** Paired device ID (the other device in the pairing) */
  pairedWith: DeviceId;
  /** Ed25519 signature of registration payload */
  signature: Base64Url;
  /** Signature timestamp */
  signedAtMs: TimestampMs;
}

/**
 * Response after successful device registration
 */
export interface RegisterDeviceResponse {
  /** Success flag */
  ok: true;
  /** Registered device ID */
  deviceId: DeviceId;
  /** Registration timestamp */
  registeredAtMs: TimestampMs;
}

/**
 * Stored device registration in Worker KV
 */
export interface StoredDeviceRegistration {
  /** Device ID */
  deviceId: DeviceId;
  /** Ed25519 public key */
  publicKey: Base64Url;
  /** Device role */
  role: DeviceRole;
  /** Paired device ID */
  pairedWith: DeviceId;
  /** Registration timestamp */
  registeredAtMs: TimestampMs;
}

/**
 * Signature verification parameters
 */
export interface SignatureVerificationParams {
  /** Device ID for lookup */
  deviceId: DeviceId;
  /** Base64url-encoded Ed25519 signature */
  signature: Base64Url;
  /** Signature timestamp */
  signedAtMs: TimestampMs;
  /** Full payload that was signed */
  payload: string;
}

/**
 * Stored health message in Durable Object
 */
export interface StoredHealthMessage {
  /** Message ID generated by Worker */
  messageId: MessageId;
  /** Encrypted health envelope */
  envelope: import("./envelope.js").EncryptedHealthEnvelope;
  /** Sender device ID */
  deviceId: DeviceId;
  /** Receipt timestamp */
  receivedAtMs: TimestampMs;
  /** Expiration timestamp */
  expiresAtMs: TimestampMs;
}

/**
 * Constants for device identity
 */
export const DEVICE_ID_LENGTH = 64 as const;
export const PUBLIC_KEY_LENGTH = 32 as const;
export const SIGNATURE_MAX_DRIFT_MS = 300000; // 5 minutes